kappashift/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shift/', include('shiftmakeapp.urls', namespace='shift')),
    path('', include('kappashiftapp.urls'))
]

shiftmakeapp/urls.py
from django.urls import path, include
from .views import CompetitionCreate, timetableupdatefunc, timetablesuggest, timetableregister, entryfunc, HistoryView, HistoryDetail, shiftcreate


app_name = 'shift'
urlpatterns = [
    path('competition/', CompetitionCreate.as_view(), name='competition'),
    path('timetable/<int:pk>', timetableupdatefunc, name='timetable'),
    path('timetable/<int:pk>/suggest', timetablesuggest, name='suggest'),
    path('timetable/<int:pk>/register', timetableregister, name='register'),
    path('entry/<int:pk>', entryfunc, name="entry"),
    path('history', HistoryView.as_view(), name='history'),
    path('history/<int:pk>', HistoryDetail.as_view(), name='historydetail'),
    path('create/<int:pk>', shiftcreate, name='create')
]

shiftmakeapp/forms.py
from django import forms


class TimetableForm(forms.Form):
    sex = forms.ChoiceField(choices=(('M', '男'), ('W', '女')))
    distance = forms.IntegerField()
    style = forms.ChoiceField(choices=(('Fr', 'Fr'), ('Ba', 'Ba'), (
        'Br', 'Br'), ('Fly', 'Fly'), ('IM', 'IM'), ('FR', 'FR'), ('MR', 'MR')))
    start_time = forms.TimeField()

templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% block customcss %}
    {% endblock customcss %}

    <title>Kappashift</title>
  </head>
  <body>
    {% block header %}
    {% endblock header %}

    {% if messages %}
      <div class="container">
          <div class="alert alert-success">
              {% for message in messages %}
                <p> {{ message }}</p>
              {% endfor %}
          </div>
      </div>
    {% endif %}

    {% block content %}
    {% endblock content %}

    
    <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    {% block script %}
    {% endblock script %}
  </body>
</html>

templates/competitioncreate.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">試合情報登録</h1>
        <p class="lead">試合のデータを登録してください</p>
    </div>
</header>
{% endblock header %}

{% block content %}
<div class="container">
    <form action="" method="POST">{% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="form-group col-12">
                    <label for="inputName">名称</label>
                    <p>{{form.name|add_class:"form-control"|attr:"list:competition_names"}}
                    <datalist id="competition_names">
                    {% for name in name_suggest %}
                        <option value="{{name}}"></option>
                    {% endfor %}    
                    </datalist>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-3">
                    <label for="inputYear">年</label>
                    <p>{{form.year|add_class:"form-control"}}</p>
                </div>
                <div class="form-group col-3">
                    <label for="inputStartDate">開始日</label>
                    <p>{{form.start_date|add_class:"form-control"|attr:"type:date"}}</p>
                </div>
                <div class="form-group col-3">
                    <label for="inputEndDate">終了日</label>
                    <p>{{form.end_date|add_class:"form-control"|attr:"type:date"}}</p>
                </div>
                <div class="form-group col-3">
                    <label for="inputDays">日数</label>
                    <p>{{form.days|add_class:"form-control"}}</p>
                </div>
            </div>
            <div class="form-group mt-5">
                <input type="submit" value="追加" class="form-control btn btn-primary">
            </div>
        </div>
    </form>

    <a href="{% url 'top' %}" class="float-right">トップページに戻る</a>
</div>
{% endblock content %}

templates/create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">選手情報登録</h1>
        <p class="lead">選手の氏名・性別・学年・種別を入力してください</p>
    </div>
</header>
{% endblock header %}

{% block content %}
<div class="container">
    <form action="" method="POST">{% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="form-group col-6">
                    <label for="inputLastName">姓</label>
                    <p>{{form.last_name|add_class:"form-control"}}</p>
                </div>
                <div class="form-group col-6">
                    <label for="inputFirstName">名</label>
                    <p>{{form.first_name|add_class:"form-control"}}</p>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-3">
                    <label for="inputSex">性別</label>
                    <p>{{form.sex|add_class:"form-control"}}</p>
                </div>
                <div class="form-group col-4">
                    <label for="inputGrade">学年</label>
                    <p>{{form.grade|add_class:"form-control"}}</p>
                </div>
                <div class="form-group col-5">
                    <label for="inputType">種別</label>
                    <p>{{form.member_type|add_class:"form-control"}}</p>
                </div>
            </div>
            <div class="form-group mt-5">
                <input type="submit" value="追加" class="form-control btn btn-primary">
            </div>
        </div>
    </form>

    <a href="{% url 'member' %}" class="float-right">一覧に戻る</a>
</div>

{% endblock content %}

templates/delete.html
{% extends 'base.html' %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">選手リスト</h1>
        <p class="lead">現在、東京大学運動会水泳部に所属している部員のリストです。</p>
        <p class="lead">新規登録の際は下の追加ボタンよりお願いします。</p>
    </div>
</header>
{% endblock header %}

{% block content %}
<div class="container justify-content-center">
    <div class="row">
        <form method="post">
        {% csrf_token %}
        <p>{{object.last_name}} {{object.first_name}} を削除します。よろしいですか？</p>
            <input class="btn btn-danger" type="submit" value="削除する">
        </form>
    </div>
</div>
{% endblock content %}

templates/entry.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">エントリーデータ登録</h1>
        <p class="lead">各選手のエントリー種目を登録してください。</p>
    </div>
</header>
{% endblock header %}

{% block content %}

<div class="container pb-5">
    <form action="" method="POST">{% csrf_token %}
    <table class="table mt-5" id="table">
        <tr>
            <th>名前</th>
            <th>性別</th>
            <th>距離</th>
            <th>泳法</th>
        </tr>
        
        {% for item in object_list %}
            <tr>
                <td>{{item.last_name}} {{item.first_name}}</td>
                <td>{{item.sex}}</td>
                <td><input type="number" name="distance" class="form-control"></td>
                <td>
                    <select name="style" for="inputStyle" placeholder="{{item.event.style}}" class="form-control style">
                        <option value="Fr">Fr</option>
                        <option value="Ba">Ba</option>
                        <option value="Br">Br</option>
                        <option value="Fly">Fly</option>
                        <option value="IM">IM</option>
                        <option value="FR">FR</option>
                        <option value="MR">MR</option>
                    </select>
                </td>
                <td>
                <div class="form-add" id="form_add">
                    <span class="add btn btn-info" title="Add">+</span>
                </div>
                </td>
            </tr>
            <input type="hidden" name="first_name" value={{item.first_name}}>
            <input type="hidden" name="last_name" value={{item.last_name}}>
            <input type="hidden" name="sex" value={{item.sex}}>
        {% endfor %}
        
        
    </table>
    <input type="submit" value="登録" class="form-control btn btn-primary">
    </form>
</div>

{% endblock content %}

templates/history.html
{% extends 'base.html' %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4">過去シフト閲覧</h1>
        <p class="lead">過去に作成したシフトを閲覧できます。</p>
        <p><a href="{% url 'top' %}">TOPに戻る</a></p>
    </div>
</header>
{% endblock header %}

{% block content %}

<div class="container">
    <table class="table">
        <tr>
            <th>日程</th>
            <th>大会名</th>
        </tr>
        {% for item in object_list %}
            <tr>
                <td>{{item.start_date}}</td>
                <td><a href="{% url 'shift:historydetail' item.pk %}">{{item.name}}</a></td>
            </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

templates/historydetail.html
{% extends 'base.html' %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4">過去シフト閲覧</h1>
        <p class="lead">過去に作成したシフトを閲覧できます。</p>
        <p>表示中のシフト：{{object}}</p>
        <p><a href="{% url 'shift:history' %}">シフト履歴一覧に戻る</a></p>
        <p><a href="{% url 'top' %}">TOPに戻る</a></p>
        
    </div>
</header>
{% endblock header %}

{% block content %}

<div class="container">
    <table class="table">
        <tr>
            <th>Index</th>
            <th>種目</th>
            <th>開始時間</th>
            <th>出場人数</th>
            <th>ビデオ</th>
            <th>計時役員</th>
        </tr>
        {% for item in shift %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{item.event}}</td>
            <td>{{item.start_time}}</td>
            <td>{{item.member_count}}</td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<form action="" method="POST" class="form-signin">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="ログイン" class="btn btn-primary btn-block">
</form>

{% endblock content %}

templates/member.html
{% extends 'base.html' %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">選手リスト</h1>
        <p class="lead">現在、東京大学運動会水泳部に所属している部員のリストです。</p>
        <p class="lead">新規登録の際は下の追加ボタンよりお願いします。</p>
    </div>
</header>
{% endblock header %}

{% block content %}
<div class="container pb-5">
<table class="table table-bordered">
    <tr>
        <th>姓</th>
        <th>名</th>
        <th>性別</th>
        <th>学年</th>
        <th>種別</th>
        <th></th>
        <th></th>
    </tr>
    {% for item in object_list %}
    <tr>
        <td>{{item.last_name}}</td>
        <td>{{item.first_name}}</td>
        <td>{{item.sex}}</td>
        <td>{{item.grade}}</td>
        <td>{{item.member_type}}</td>
        <td><a href="{% url 'update' item.pk %}" class="text-secondary">編集</a></td>
        <td><a href="{% url 'delete' item.pk %}" class="text-secondary">削除</a></td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'create' %}" class="btn btn-primary float-right">+ 追加</a>
</div>
{% endblock content %}

templates/shiftcreate.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">シフト作成</h1>
        <p class="lead">ビデオ・計時に一年生（上級生）を配置してください。</p>
        <p>作成中の大会：{{competition}}</p>
        <p><a href="{% url 'top' %}">TOPに戻る</a></p>
    </div>
</header>
{% endblock header %}

{% block content %}

<div class="container">
    <form action="" method="POST" id="form-shift" data-length="{{object_list|length}}">{% csrf_token %}
    <table class="table mt-5" id="table">
        <tr>
            <th>Index</th>
            <th>種目</th>
            <th>開始時間</th>
            <th>出場人数</th>
            <th>ビデオ</th>
            <th>計時役員</th>
        </tr>
        {% for item in object_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{item.event}}</td>
                <td>{{item.start_time}}</td>
                <td><p id="member-count-{{forloop.counter}}" data-count="{{item.member_count}}">{{item.member_count}}</p></td>
                <td>
                    <select name="video" id="video-select-{{forloop.counter}}" class="form-control">
                        {% for m in freshman %}
                            <option value="{{m.id}}">{{m}}</option>
                        {% endfor %}
                    </select>
                </td>
                <td>
                    <select name="timekeep" id="" class="form-control">
                        {% for m in freshman %}
                            <option value="{{m.id}}">{{m}}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
        {% endfor %}
    </table>
    <p><input type="submit" class="form-control" value="上記の内容で登録"></p>
    </form>
</div>

{% endblock content %}

{% block script %}
    <script src="{% static 'app.js' %}"></script>
{% endblock script %}

templates/timetable.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">タイムテーブル登録</h1>
        <p class="lead">試合のタイムテーブルを登録してください</p>
    </div>
</header>
{% endblock header %}

{% block content %}
<div class="container">
    <div class="suggestion">
        <form action="{% url 'shift:suggest' pk %}" method="POST" class="form-inline">{% csrf_token %}
            <label class="m-3">過去の試合データを参照</label>
            <select name="competition" class="form-control m-3">
                {% for s in suggest %}
                    <option value={{s.id}}>{{s.year}}{{s.name}}</option>
                {% endfor %}
            </select>
            <input type="submit" value="表示" class="form-control m-3">
        </form>
    </div>
    <form action="{% url 'shift:register' pk %}" method="post" id="form" data-length="{{ object_list|length }}">
    {% csrf_token %}
    {{ formset.management_form }}
        <table class="table mt-5" id="table">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>性別</th>
                    <th>距離</th>
                    <th>種目</th>
                    <th>開始時刻</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% if object_list %}
                {% for item in object_list %}
                    
                    <tr class="field field-{{forloop.counter}}">
                        <td>{{forloop.counter}}</td>
                        <td>
                            <select name="sex" id="id_sex" class="form-control">
                            {% for p,q in formset.form.fields.sex.choices %}
                                {% if item.event.sex == p %}
                                    <option value="{{p}}" selected>{{q}}</option>
                                {% else %}
                                    <option value="{{p}}">{{q}}</option>
                                {% endif %}
                            {% endfor %}
                            </select>
                        </td>
                        <td>
                            <input type="number" name="distance" value="{{item.event.distance}}" class="form-control" required id="id_distance">
                        </td>
                        <td>
                            <select name="style" id="id_style" class="form-control">
                            {% for p,q in formset.form.fields.style.choices %}
                                {% if item.event.style == p %}
                                    <option value="{{p}}" selected>{{q}}</option>
                                {% else %}
                                    <option value="{{p}}">{{q}}</option>
                                {% endif %}
                            {% endfor %}
                            </select>
                        </td>
                        <td>
                            <input type="text" name="start_time" value="{{item.start_time|date:"h:i"}}" class="form-control" required id="id_start_time">
                        </td>
                        <td></td>
                        <td>
                            <div class="form-delete" id="form_delete">
                                <span class="delete btn btn-danger" title="Delete" data-count="{{forloop.counter}}">×</span>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
            <tr class="form-empty field field-{{object_list|length|add:"1"}}">
                <td>{{object_list|length|add:"1"}}</td>
                {% for field in formset.form %}
                    <td>
                        {{field|add_class:"form-control"}}
                    </td>
                {% endfor %}
                <td></td>
                <td>
                    <div class="form-delete" id="form_delete">
                        <span class="delete btn btn-danger" title="Delete" data-count="{{object_list|length|add:"1"}}">×</span>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <div class="form-add" id="form_add">
                        <span class="add btn btn-info" title="Add">+</span>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <div>
                        <input type="submit" value="登録" class="form-control">
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
</div>


{% endblock content %}

{% block script %}
<script>
    $(function () {
        $(document).on('click', 'span.add', function () {
            frm_emp = $(".form-empty").last();
            frm_nxt = frm_emp.clone();
            frm_nxt.insertAfter(frm_emp);
        })

        $(document).on('click', 'span.delete', function () {
            cnt = $(this).data("count");
            $('.field-' + cnt).remove();
        })

        $('#form').submit(function() {  // フォームを送信する直前

            // フォームの入力欄の数を指定する
            const text = $('.field');
            console.log(text);
            $('[name=form-TOTAL_FORMS]').val(text.length);

            // それぞれの入力欄の__prefix__をindexで置換する
            text.each(function(index, element){
                html = $(element).html().replace(/__prefix__/g, index);
                value_sex = $(element).find("[name='sex']").val();
                value_dist = $(element).find("input[name='distance']").val();
                value_style = $(element).find("[name='style']").val();
                value_time = $(element).find("input[name='start_time']").val();   // valueが消えるので保存しておく
                $(element).html(html);
                $(element).find("[name='sex']").val(value_sex);
                $(element).find("input[name='distance']").val(value_dist);
                $(element).find("[name='style']").val(value_style);
                $(element).find("input[name='start_time']").val(value_time);
        });

    });
    })
    </script>
{% endblock script %}

templates/top.html
{% extends 'base.html' %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4">Kappashift</h1>
        <p class="lead">ここには説明文が入ります</p>
    </div>
</header>
{% endblock header %}

{% block content %}
<div class="container justify-content-center mt-5">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body"> 
                    <h5 class="card-title">過去シフト閲覧</h5>
                    <p class="card-text">過去に作ったシフトを閲覧できます。</p>
                    <a href="{% url 'shift:history' %}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-body"> 
                    <h5 class="card-title">新規シフト作成</h5>
                    <p class="card-text">過去に作ったシフトを閲覧できます。</p>
                    <a href="{% url 'shift:competition' %}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-body"> 
                    <h5 class="card-title">選手情報登録</h5>
                    <p class="card-text">所属する部員の情報を登録・編集します。</p>
                    <a href="{% url 'member' %}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/update.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block header %}
<header class="jumbotron jumbotron-fluid">
    <div class="container p-5">
        <h1 class="display-4 mb-3">選手情報登録</h1>
        <p class="lead">選手の氏名・性別・学年・種別を入力してください</p>
    </div>
</header>
{% endblock header %}

{% block content %}
<div class="container">
    <form action="" method="POST">{% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="form-group col-6">
                    <label for="inputLastName">姓</label>
                    <p>{{form.last_name|add_class:"form-control"}}</p>
                </div>
                <div class="form-group col-6">
                    <label for="inputFirstName">名</label>
                    <p>{{form.first_name|add_class:"form-control"}}</p>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-3">
                    <label for="inputSex">性別</label>
                    <p>{{form.sex|add_class:"form-control"}}</p>
                </div>
                <div class="form-group col-4">
                    <label for="inputGrade">学年</label>
                    <p>{{form.grade|add_class:"form-control"}}</p>
                </div>
                <div class="form-group col-5">
                    <label for="inputType">種別</label>
                    <p>{{form.member_type|add_class:"form-control"}}</p>
                </div>
            </div>
            <div class="form-group mt-5">
                <input type="submit" value="変更を保存" class="form-control btn btn-primary">
            </div>
        </div>
    </form>

    <a href="{% url 'member' %}" class="float-right">一覧に戻る</a>
</div>

{% endblock content %}